
__merge__: ../../api/comp_test.yaml

functionality:
  name: process_multiomics
  namespace: "workflows"
  info:
    label: process_multiomics
    summary: "Processes multiomics data to generate rna and atac adatas"

  arguments:
    - name: --multiome_counts
      type: file 
      required: true
      direction: input
      default: resources/datasets_raw/multiome_counts.h5ad
      description: multiomics data at baseline

    - name: --multiomics_rna
      type: file 
      required: true
      direction: output
      default: resources/grn-benchmark/multiomics_rna.h5ad
    - name: --multiomics_atac
      type: file 
      required: true
      direction: output
      default: resources/grn-benchmark/multiomics_atac.h5ad
    
    - name: --rna_rds
      type: file
      required: true
      direction: output
      default: resources/grn-benchmark/multiomics_r/rna.rds
    - name: --atac_rds
      type: file
      required: true
      direction: output
      default: resources/grn-benchmark/multiomics_r/atac.rds
    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: multiomics/format_data 
    - name: multiomics/multiome_matrix
    - name: multiomics/format_resources_r 
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
