functionality:
  name: run_robustness_analysis
  namespace: "workflows"
  info:
    label: run_robustness_analysis
    summary: "Evaluates GRNs and provides scores using regression analysis."
  argument_groups:
    - name: Inputs
      arguments:
        - name: --perturbation_data
          type: file
          direction: input
        - name: --layer
          type: string
          direction: input
        - name: --prediction
          type: file
          direction: input
          required: false
        - name: --subsample
          type: integer
          direction: input
          default: 200
        - name: --reg_type
          type: string
          direction: input
          default: ridge
        - name: --method_id 
          type: string 
          direction: input 
          required: True
          example: collectri
        - name: --max_workers
          type: integer
          direction: input
          required: True
        - name: --consensus
          type: file
          required: false
          direction: input
          default: resources/prior/consensus.json
        - name: --degree
          type: integer
          required: false
          direction: input
          default: 20
        - name: --noise_type
          type: string
          required: false
          direction: input
          default: weight
        
        - name: --tf_all
          type: file
          required: false
          direction: input
        
        
    - name: Outputs
      arguments:
        - name: "--scores"
          type: file
          required: true
          direction: output
          default: "scores.yaml"
        - name: "--metric_configs"
          type: file
          required: true
          direction: output
          default: metric_configs.yaml
    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: ../../api/task_info.yaml
  dependencies:
    - name: common/extract_metadata
      repository: openproblemsv2
    - name: metrics/regression_1
    - name: metrics/regression_2
    - name: robustness_analysis/noise_grn
  repositories:
    - name: openproblemsv2
      type: github
      repo: openproblems-bio/openproblems-v2
      tag: main_build
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
