functionality:
  name: "scglue"
  namespace: "methods"
  version: "dev"
  arguments:
  - type: "file"
    name: "--multiomics_rna"
    info:
      label: "multiomics rna"
      summary: "RNA expression for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_atac"
    info:
      label: "multiomics atac"
      summary: "Peak data for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources/grn-benchmark/multiomics_atac.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    info:
      label: "GRN"
      summary: "GRN prediction"
      file_type: "csv"
      columns:
      - name: "source"
        description: "Source of regulation"
        type: "string"
        required: true
      - name: "target"
        description: "Target of regulation"
        type: "string"
        required: true
      - name: "weight"
        description: "Weight of regulation"
        type: "float"
        required: true
    example:
    - "resources/grn-benchmark/collectri.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_model"
    info:
      label: "Model"
      summary: "Optional model output. If no value is passed, the model will be removed\
        \ at the end of the run."
      file_type: "directory"
    example:
    - "resources/grn-benchmark/model"
    must_exist: false
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/grn-benchmark"
    dest: "/resources/grn-benchmark"
  info:
    label: "Scglue"
    summary: "FILL IN: A one sentence summary of this method."
    description: "FILL IN: A (multi-line) description of how this method works.\n"
    documentation_url: "https://url.to/the/documentation"
    repository_url: "https://github.com/organisation/repository"
    type: "method"
    type_info:
      label: "Method"
      summary: "A GRN inference method"
      description: "A method for inferring GRN from expression data.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/openproblems-bio/base_python:1.0.4"
  target_organization: "openproblems-bio"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/openproblems-v2"
  setup:
  - type: "python"
    user: false
    upgrade: true
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/mnt/c/Users/nourisa/Documents/testProjs/ongoing/task-grn-benchmark/src/methods/scglue/config.vsh.yaml"
  platform: "docker"
  output: "/mnt/c/Users/nourisa/Documents/testProjs/ongoing/task-grn-benchmark/target/docker/methods/scglue"
  executable: "/mnt/c/Users/nourisa/Documents/testProjs/ongoing/task-grn-benchmark/target/docker/methods/scglue/scglue"
  viash_version: "0.8.0"
  git_commit: "2950eb11f0291e58a2caa1764812eafe3e52b788"
  git_remote: "git@github.com:openproblems-bio/task-grn-benchmark.git"
