__merge__: ../../api/comp_method.yaml

functionality:
  name: figr
  info:
    label: figr
    summary: "GRN inference using figr"
    description: |
      GRN inference using figr.
    documentation_url: https://buenrostrolab.github.io/FigR/articles/FigR_shareseq.html
  arguments:
    - name: --multiomics_rna
      type: file
      example: resources/grn-benchmark/multiomics_r/rna.rds
      info:
        label: multiomics_rna
        summary: "Multiomics rna in rds format"
        file_type: rds
        columns: 
          - name: dummpy
            type: string
            required: false
      required: true
    - name: --multiomics_atac
      type: file
      example: resources/grn-benchmark/multiomics_r/atac.rds
      info:
        label: multiomics_atac
        summary: "Multiomics atac in rds format"
        file_type: rds
        columns: 
          - name: dummpy
            type: string
            required: false
      required: true
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: true
      direction: output
    
    - name: --cell_topic
      type: file
      example: resources/grn-benchmark/supp/cell_topic.csv
      info:
        label: Cell topic probability database
        summary: "annotation file"
        file_type: csv
        columns: 
          - name: topic
            type: string
            required: false
      required: true

    - name: --temp_dir
      type: string
      direction: input
      default: 'output/figr'
    - name: --num_workers
      type: integer
      direction: input
      default: 4
    - name: --n_topics
      type: integer 
      direction: input
      default: 48
  resources:
    - type: r_script
      path: script.R


platforms:
  - type: docker
    image: janursa/figr:19-08-2024
    # setup:
    #   - type: r
    #     packages: [dplyr, FNN, chromVAR, doParallel, BuenColors, FigR, BSgenome.Hsapiens.UCSC.hg38]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
