functionality:
  name: "process_multiomics"
  namespace: "workflows"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--multiome_counts"
    description: "multiomics data at baseline"
    info: null
    default:
    - "resources/datasets_raw/multiome_counts.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_rna"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_atac"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_atac.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--rna_rds"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_rna.rds"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--atac_rds"
    info: null
    default:
    - "resources/grn-benchmark/multiomics_atac.rds"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/grn-benchmark"
    dest: "resources/grn-benchmark"
  info:
    label: "process_multiomics"
    summary: "Processes multiomics data to generate rna and atac adatas"
  status: "enabled"
  dependencies:
  - name: "multiomics/format_data"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_data/config.vsh.yaml"
    configInfo:
      functionalityName: "format_data"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_data/config.vsh.yaml"
      functionalityNamespace: "multiomics"
      output: ""
      platform: ""
      git_commit: "e7a9781f1e77339a879199abf5977d777cf27ece"
      executable: "/nextflow/multiomics/format_data/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/multiomics/format_data"
  - name: "multiomics/multiome_matrix"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/multiome_matrix/config.vsh.yaml"
    configInfo:
      functionalityName: "multiome_matrix"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/multiome_matrix/config.vsh.yaml"
      functionalityNamespace: "multiomics"
      output: ""
      platform: ""
      git_commit: "e7a9781f1e77339a879199abf5977d777cf27ece"
      executable: "/nextflow/multiomics/multiome_matrix/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/multiomics/multiome_matrix"
  - name: "multiomics/format_resources_r"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_resources_r/config.vsh.yaml"
    configInfo:
      functionalityName: "format_resources_r"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/process_data/multiomics/format_resources_r/config.vsh.yaml"
      functionalityNamespace: "multiomics"
      output: ""
      platform: ""
      git_commit: "e7a9781f1e77339a879199abf5977d777cf27ece"
      executable: "/nextflow/multiomics/format_resources_r/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/multiomics/format_resources_r"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/workflows/process_multiomics/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/process_multiomics"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/process_multiomics/main.nf"
  viash_version: "0.8.6"
  git_commit: "e7a9781f1e77339a879199abf5977d777cf27ece"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
