__merge__: ../../../api/comp_method.yaml

functionality:
  name: genie3
  namespace: "grn_methods"
  info:
    label: genie3
    
    summary: "GRN inference using GENIE3"
    description: |
      GRN inference using GENIE3.
    documentation_url: https://www.bioconductor.org/packages/release/bioc/html/GENIE3.html
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: continuumio/anaconda3:2024.02-1
    setup:
      - type: docker
        run: |
          conda install -y -c bioconda arboreto pandas
      - type: python
        packages: [ anndata ]
  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
