__merge__: ../../api/comp_metric.yaml

name: sem
namespace: "metrics"
info:
  label: SEM
  summary: Structural equation based metric

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/utils/config.py
    dest: config.py

engines:
  - type: docker
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: []
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]