__merge__: ../../api/comp_metric.yaml

name: vc
namespace: "metrics"
info:
  label: Virtual Cell
  summary: Predicts gene expression for OOD conditions using encoded perturbation and control expression


resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/utils/config.py
    dest: config.py

engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ torch==2.4.1]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]