__merge__: ../../api/comp_metric.yaml

name: regression
namespace: "metrics"
info:
  label: regression
  summary: Calculates regression scores 2
  description: |
    Calculates regression scores 2
  metrics:
    - name: r2-theta-0.1
      label: R2 (precision)
      summary: Captures the perfomance for the top regulatory links
      description: |
        Captures the perfomance for the top regulatory links
      min: -Inf
      max: 1
      maximize: true
    - name: r2-theta-0.5
      label: R2 (balanced)
      summary: Balanced performance scores considering both prevision and recall 
      description: |
        Balanced performance scores considering both prevision and recall
      min: -Inf
      max: 1
      maximize: true
    - name: r2-theta-1.0
      label: R2 (recall)
      summary: Captures the perfomance for the more broad regulatory links (recall)
      description: |
        Captures the perfomance for the more broad regulatory links (recall)
      min: -Inf
      max: 1
      maximize: true

  
resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/metrics/regression/helper.py
    dest: helper_regression.py
  - path: /src/metrics/ws_distance/helper.py
    dest: helper_ws_distance.py
  - path: /src/metrics/sem/helper.py
    dest: helper_sem.py
  - path: /src/metrics/tf_recovery/helper.py
    dest: helper_tf_recovery.py
  - path: /src/metrics/tf_binding/helper.py
    dest: helper_tf_binding.py
  - path: /src/metrics/replica_consistency/helper.py
    dest: helper_replica_consistency.py


engines:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 , tqdm_joblib==0.0.5]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]