
functionality:
  name: run_grn_evaluation
  namespace: "workflows"
  info:
    label: run_grn_evaluation
    summary: "Evaluates GRNs and provides scores using regression analysis."

  argument_groups:
    - name: Inputs
      arguments:
        - name: --perturbation_data
          type: file
          must_exist: True
          direction: input
        - name: --layer
          type: string
          direction: input
        - name: --prediction
          type: file
          direction: input
        - name: --subsample
          type: integer
          direction: input
          default: 2
        - name: --reg_type
          type: string
          direction: input
          default: ridge
        

    - name: Outputs
      arguments:
        - name: "--scores"
          type: file
          required: true
          direction: output
          default: "scores.yaml"
          # description: A csv file containing the scores with each row corrosponding to a layer.
          # default: scores.csv
        - name: "--metric_configs"
          type: file
          required: true
          direction: output
          default: metric_configs.yaml

    # - name: Arguments
    #   arguments: 
    #     - name: "--predictions" 
    #       type: string
    #       multiple: true
    #       description: A list of GRN models 
    #     - name: "--layers"
    #       type: string
    #       multiple: true
    #       description: A list of GRN models 
    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: ../../api/task_info.yaml
  dependencies:
    - name: common/extract_metadata
      repository: openproblemsv2
    - name: metrics/regression_2 
    - name: metrics/regression_1
  repositories:
    - name: openproblemsv2
      type: github
      repo: openproblems-bio/openproblems-v2
      tag: main_build
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
