__merge__: /src/api/comp_method.yaml

name: celloracle
namespace: "grn_methods"
label: celloracle
summary: "GRN inference using celloracle"
description: |
  GRN inference using celloracle.
links:
  documentation: https://morris-lab.github.io/CellOracle.documentation/   
arguments:
  - name: --base_grn
    type: file
    direction: output
    default: celloracle_output/base_grn.csv
  - name: --annotated_peaks
    type: file
    direction: output
    default: celloracle_output/annotated_peaks.csv

  # - name: --links
  #   type: file
  #   direction: output
  #   default: output/celloracle/links.celloracle.links 
resources:
  - type: python_script
    path: script.py
  - path: main.py

engines:
  - type: docker
    image: kenjikamimoto126/celloracle_ubuntu:0.18.0
    __merge__: /src/api/base_requirements.yaml

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [onedaytime, highmem, midcpu]
