functionality:
  name: batch_correction_evaluation
  namespace: "perturbation"
  info:
    label: batch_correction_evaluation
    summary: "Evaluate batch correction using different metrics."
  
  arguments:
    - name: --perturbation_data
      __merge__: ../../../api/file_perturbation_h5ad.yaml
      required: false
      direction: input
      default: resources/grn-benchmark/perturbation_data.h5ad
    - name: --output
      type: file
      required: true 
      direction: output
      default: output/batch_correction_metrics.csv

  resources:
    - type: python_script
      path: script.py
    - path: helper.py
platforms:
  - type: docker
    # image: ghcr.io/openproblems-bio/base_python:1.0.4
    image: ghcr.io/openproblems-bio/base_images/r:1.1.0
    
    setup:
      - type: python
        packages: [lightgbm==4.5.0, scib==1.1.5, louvain==0.8.2, rpy2]
      # - type: r
      #   packages:
      # install.packages('remotes')
      # remotes::install_github('theislab/kBET')


  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
