__merge__: ../../api/comp_metric.yaml

name: rc_tf_act
namespace: "metrics"
info:
  label: Replica Consistency TF Activity
  summary: Replica consistency of TF activity scores

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/utils/config.py
    dest: config.py

engines:
  - type: docker
    image: python:3.10
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ decoupler==2.1.1]
        
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]
