__merge__: ../../../api/comp_method.yaml

functionality:
  name: scsgl
  namespace: "grn_methods"
  info:
    label: scsgl
    summary: "GRN inference using SCSGL"
    description: |
      GRN inference using SCSGL.
    documentation_url: https://doi.org/10.1101/2021.07.08.451697
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: apassemi/scsgl
    setup:
      - type: python
        packages: [ anndata, numba==0.53.1, scipy==1.6.3, pandas==1.2.4, rpy2==3.4.4, numpy==1.20.2, scikit-learn==0.24.1, PyYAML==6.0.2 ]
  - type: native
  - type: nextflow
    directives:
      label: [onedaytime, midmem,midcpu]
