

name: run_grn_inference
namespace: "workflows"

argument_groups:
  - name: Inputs
    arguments:
      - name: --rna
        type: file
        direction: input
        required: True
      - name: --rna_all
        type: file
        direction: input
      - name: --atac
        type: file
        direction: input
      - name: --num_workers
        type: integer
        direction: input
        required: True
      - name: --tf_all
        type: file
        required: false
        direction: input
      - name: --layer
        type: string
        required: false
        direction: input
      - name: --apply_tf_methods
        type: boolean
        required: false
        direction: input
        default: true
      - name: --temp_dir
        type: string
        required: false
        direction: input
        default: 'temp_dir'
  - name: Arguments
    arguments: 
      - name: "--method_ids"
        type: string
        multiple: true
        description: A list of method ids to run. If not specified, all methods will be run.
      - name: "--metric_ids"
        type: string
        multiple: true
        description: A list of metric ids to run. If not specified, all metric will be run.
  
      

  - name: Outputs
    arguments:
      - name: "--scores"
        type: file
        required: true
        direction: output
        description: A yaml file containing the scores of each of the methods
        default: score_uns.yaml
      - name: "--method_configs"
        type: file
        required: true
        direction: output
        default: method_configs.yaml
      - name: "--metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
      - name: "--dataset_uns"
        type: file
        required: true
        direction: output
        default: dataset_uns.yaml
      - name: "--task_info"
        type: file
        required: true
        direction: output
        default: task_info.yaml

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /_viash.yaml

dependencies:
  - name: metrics/dummy_metric 
  - name: metrics/ws_distance
  - name: utils/extract_uns_metadata
    repository: openproblems
  # ---- single omics
  - name: grn_methods/portia
  - name: grn_methods/grnboost
  - name: grn_methods/scenic
  # - name: grn_methods/ppcor 
  - name: grn_methods/scprint 
  - name: grn_methods/scgpt
  - name: grn_methods/geneformer
  
  # ---- multiomics 
  - name: grn_methods/celloracle
  - name: grn_methods/scglue
  - name: grn_methods/figr
  - name: grn_methods/scenicplus
  - name: grn_methods/granie
  - name: grn_methods/dictys
  # ---- baselines
  - name: methods/pearson_corr
  - name: methods/negative_control
  - name: methods/positive_control
  - name: methods/spearman_corr

runners:
  - type: executable
  - type: nextflow
    config:
      script: |
        process.errorStrategy = 'ignore'
        trace {
            enabled = true
            overwrite = true
            file = "${params.publish_dir}/trace.txt"
        }

