__merge__: ../../api/comp_metric.yaml

name: all_metrics
namespace: "metrics"
info:
  label: All metrics
  summary: A wrapper component to compute all metrics

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/metrics/regression/helper.py
    dest: regression_helper.py
  - path: /src/metrics/ws_distance/helper.py
    dest: ws_helper.py
  - path: /src/metrics/sem/helper.py
    dest: sem_helper.py
  - path: /src/metrics/tf_recovery/helper.py
    dest: tf_recovery_helper.py
  - path: /src/metrics/tf_binding/helper.py
    dest: tf_binding_helper.py
  - path: /src/metrics/replica_consistency/helper.py
    dest: replica_consistency_helper.py
  - path: /src/utils/dataset_config.py
    dest: dataset_config.py
  - path: /src/metrics/metrics_config.py
    dest: metrics_config.py
  
  
  

engines:
  - type: docker
    image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ lightgbm==4.3.0, numpy==1.26.4 , tqdm_joblib==0.0.5, decoupler==2.1.1]


runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]