__merge__: ../../../api/comp_method.yaml

functionality:
  name: ennet
  namespace: "grn_methods"
  info:
    label: ennet
    summary: "GRN inference using ENNET"
    description: |
      GRN inference using ENNET.
    documentation_url: https://doi.org/10.1186/1752-0509-7-106
  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: janursa/figr:19-08-2024
    setup:
      - type: r
        packages: [ foreach, plyr, anndata, dplyr ]
      - type: docker
        run: |
          wget http://github.com/slawekj/ennet/archive/master.tar.gz -O ennet.tar.gz && \
          tar -xvzf ennet.tar.gz && \
          cd ennet-master && \
          R CMD build ennet && \
          R CMD INSTALL ennet
  - type: native
  - type: nextflow
    directives:
      label: [threedaystime,midmem,midcpu]
