__merge__: ../../../api/comp_test.yaml

functionality:
  name: batch_correction_scgen
  namespace: "perturbation"
  info:
    label: batch_correction_scgen
    summary: "Correct batch effects using scgen"
  
  arguments:
    - name: --perturbation_data
      type: file
      info:
        label: perturbation
        summary: "Perturbation dataset for benchmarking."
        file_type: h5ad
        slots:
          layers:
            - name: n_counts
              type: double
              description: "Pseudobulked values using mean approach"
              required: true
            - name: pearson
              type: double
              description: "Normalized values using pearson residuals"
              required: true
            - name: lognorm
              type: double
              description: "Normalized values using shifted logarithm "
              required: true
      required: false
      direction: input
      default: resources/grn-benchmark/perturbation_data.h5ad 
      example: resources_test/grn-benchmark/perturbation_data.h5ad 
    - name: --perturbation_data_bc
      type: file
      info:
        label: perturbation
        summary: "Perturbation dataset for benchmarking."
        file_type: h5ad
        slots:
          layers:
            - name: n_counts
              type: double
              description: "Pseudobulked values using mean approach"
              required: true
            - name: pearson
              type: double
              description: "Normalized values using pearson residuals"
              required: true
            - name: lognorm
              type: double
              description: "Normalized values using shifted logarithm "
              required: true
            - name: scgen_lognorm
              type: double
              description: "Batch correction using scgen on lognorm data"
              required: true
            - name: scgen_pearson
              type: double
              description: "Batch correction using scgen on pearson data"
              required: true
      required: false
      direction: input
      default: resources/grn-benchmark/perturbation_data.h5ad 
      example: resources_test/grn-benchmark/perturbation_data.h5ad 

  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: janursa/scgen:19-08-2024

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
