functionality:
  name: "run_benchmark_single_omics"
  namespace: "workflows"
  version: "build-main"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--multiomics_rna"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--multiomics_atac"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--perturbation_data"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--prediction"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--subsample"
      info: null
      default:
      - 2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--reg_type"
      info: null
      default:
      - "ridge"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--max_workers"
      info: null
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--tf_all"
      info: null
      default:
      - "resources/prior/tf_all.csv"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--consensus"
      info: null
      default:
      - "resources/prior/consensus.json"
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--layer"
      info: null
      default:
      - "pearson"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_config_file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vocab_file"
      info: null
      must_exist: true
      create_parent: true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--scores"
      info: null
      default:
      - "scores.yaml"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "string"
      name: "--method_ids"
      description: "A list of method ids to run. If not specified, all methods will\
        \ be run."
      info: null
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--metric_ids"
      description: "A list of metric ids to run. If not specified, all metric will\
        \ be run."
      info: null
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "../../api/task_info.yaml"
  info:
    label: "run_benchmark_single_omics"
    summary: "Infer GRNs and evaluate each prediction for single omics grns"
  status: "enabled"
  dependencies:
  - name: "common/extract_metadata"
    repository:
      type: "github"
      name: ""
      repo: "openproblems-bio/openproblems"
      tag: "v2.0.0"
      localPath: "/tmp/viash_hub_repo5522273892850718400"
    foundConfigPath: "/tmp/viash_hub_repo5522273892850718400/target/nextflow/common/extract_metadata/.config.vsh.yaml"
    configInfo:
      functionalityName: "extract_metadata"
      git_tag: "v1.0.0-1413-gb782e93f"
      git_remote: "https://github.com/openproblems-bio/openproblems"
      viash_version: "0.8.6"
      config: "/home/runner/work/openproblems/openproblems/src/common/extract_metadata/config.vsh.yaml"
      functionalityNamespace: "common"
      output: "/home/runner/work/openproblems/openproblems/target/nextflow/common/extract_metadata"
      platform: "nextflow"
      git_commit: "b782e93f596e0060953ca0260098b8ae2569194b"
      executable: "/home/runner/work/openproblems/openproblems/target/nextflow/common/extract_metadata/extract_metadata"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/dependencies/github/openproblems-bio/openproblems/v2.0.0/nextflow/common/extract_metadata"
  - name: "metrics/regression_2"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/metrics/regression_2/config.vsh.yaml"
    configInfo:
      functionalityName: "regression_2"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/metrics/regression_2/config.vsh.yaml"
      functionalityNamespace: "metrics"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/metrics/regression_2/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/metrics/regression_2"
  - name: "metrics/regression_1"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/metrics/regression_1/config.vsh.yaml"
    configInfo:
      functionalityName: "regression_1"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/metrics/regression_1/config.vsh.yaml"
      functionalityNamespace: "metrics"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/metrics/regression_1/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/metrics/regression_1"
  - name: "control_methods/positive_control"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/control_methods/positive_control/config.vsh.yaml"
    configInfo:
      functionalityName: "positive_control"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/control_methods/positive_control/config.vsh.yaml"
      functionalityNamespace: "control_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/control_methods/positive_control/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/control_methods/positive_control"
  - name: "control_methods/negative_control"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/control_methods/negative_control/config.vsh.yaml"
    configInfo:
      functionalityName: "negative_control"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/control_methods/negative_control/config.vsh.yaml"
      functionalityNamespace: "control_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/control_methods/negative_control/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/control_methods/negative_control"
  - name: "grn_methods/portia"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/portia/config.vsh.yaml"
    configInfo:
      functionalityName: "portia"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/portia/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/portia/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/portia"
  - name: "grn_methods/ennet"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/ennet/config.vsh.yaml"
    configInfo:
      functionalityName: "ennet"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/ennet/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/ennet/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/ennet"
  - name: "grn_methods/genie3"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/genie3/config.vsh.yaml"
    configInfo:
      functionalityName: "genie3"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/genie3/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/genie3/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/genie3"
  - name: "grn_methods/grnboost2"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/grnboost2/config.vsh.yaml"
    configInfo:
      functionalityName: "grnboost2"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/grnboost2/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/grnboost2/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/grnboost2"
  - name: "grn_methods/pidc"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/pidc/config.vsh.yaml"
    configInfo:
      functionalityName: "pidc"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/pidc/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/pidc/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/pidc"
  - name: "grn_methods/ppcor"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/ppcor/config.vsh.yaml"
    configInfo:
      functionalityName: "ppcor"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/ppcor/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/ppcor/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/ppcor"
  - name: "grn_methods/scsgl"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/scsgl/config.vsh.yaml"
    configInfo:
      functionalityName: "scsgl"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/scsgl/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/scsgl/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/scsgl"
  - name: "grn_methods/tigress"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/tigress/config.vsh.yaml"
    configInfo:
      functionalityName: "tigress"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/tigress/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/tigress/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/tigress"
  - name: "grn_methods/scgpt"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/scgpt/config.vsh.yaml"
    configInfo:
      functionalityName: "scgpt"
      git_tag: ""
      git_remote: "https://github.com/openproblems-bio/task_grn_inference"
      viash_version: "0.8.6"
      config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/single_omics/scgpt/config.vsh.yaml"
      functionalityNamespace: "grn_methods"
      output: ""
      platform: ""
      git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
      executable: "/nextflow/grn_methods/scgpt/main.nf"
    writtenPath: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/grn_methods/scgpt"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "v2.0.0"
    localPath: ""
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "threedaystime"
    - "midmem"
    - "highcpu"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/workflows/run_benchmark_single_omics/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/run_benchmark_single_omics"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/nextflow/workflows/run_benchmark_single_omics/main.nf"
  viash_version: "0.8.6"
  git_commit: "4a35f67cd98d95d25407cb74cfb689a896801e16"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
