__merge__: ../../../api/comp_method.yaml

functionality:
  name: tigress
  namespace: "grn_methods"
  info:
    label: tigress
    summary: "GRN inference using TIGRESS"
    description: |
      GRN inference using TIGRESS.
    documentation_url: https://rdrr.io/github/jpvert/tigress/man/tigress.html
  
  resources:
    - type: r_script
      path: script.R

platforms:
  - type: docker
    image: janursa/figr:19-08-2024
    setup:
      - type: r
        packages: [ devtools, foreach, plyr, doRNG, glmnet, randomForest, anndata, dplyr ]
      - type: docker
        run: |
          Rscript -e 'library(devtools); install_github("jpvert/tigress")'
  - type: native
  - type: nextflow
    directives:
      label: [midtime, midmem, highcpu]
