functionality:
  name: "run_benchmark"
  namespace: "workflows"
  argument_groups:
    - name: Inputs
      arguments:
        - name: --multiomics_rna
          __merge__: ../../api/file_multiomics_rna_h5ad.yaml
          required: true
          direction: input
        - name: --multiomics_atac
          __merge__: ../../api/file_multiomics_atac_h5ad.yaml
          required: false
          direction: input
        

    - name: Outputs
      arguments:
        - name: "--scores"
          type: file
          required: true
          direction: output
          description: A yaml file containing the scores of each of the methods
          default: score_uns.yaml
        - name: "--method_configs"
          type: file
          required: true
          direction: output
          default: method_configs.yaml
        - name: "--dataset_uns"
          type: file
          required: true
          direction: output
          default: dataset_uns.yaml
        - name: "--task_info"
          type: file
          required: true
          direction: output
          default: task_info.yaml
    - name: Arguments
      arguments:
        - name: "--method_ids"
          type: string
          multiple: true
          description: A list of method ids to run. If not specified, all methods will be run.


  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: "../../api/task_info.yaml"
  dependencies:
  - name: common/extract_metadata
    repository: openproblemsv2
  # dependencies:
  #   # - name: common/extract_metadata
  #   #   repository: openproblemsv2
  #   # - name: control_methods/positive_control
  #   # - name: control_methods/negative_control
  #   - name: methods/scglue
  #   - name: metrics/regression_1
  # repositories:
  #   - name: openproblemsv2
  #     type: github
  #     repo: openproblems-bio/openproblems-v2
  #     tag: main_build
platforms:
  - type: nextflow
    config:
      script: |
        process.errorStrategy = 'ignore'
        trace {
            enabled = true
            overwrite = true
            file = "${params.publish_dir}/trace.txt"
        }
