name: "run_grn_evaluation"
namespace: "workflows"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--evaluation_data"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--evaluation_data_de"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--evaluation_data_sc"
    info: null
    example:
    - "resources_test/datasets_raw/adamson_sc_counts.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--prediction"
    info: null
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--tf_all"
    info: null
    example:
    - "resources_test/grn_benchmark/prior/tf_all.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reg_type"
    description: "name of regretion to use"
    info: null
    default:
    - "ridge"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--subsample"
    description: "number of samples randomly drawn from perturbation data"
    info: null
    default:
    - -1
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--num_workers"
    info: null
    default:
    - 4
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--apply_tf"
    info: null
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--layer"
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--regulators_consensus"
    info: null
    example:
    - "resources_test/grn_benchmark/prior/regulators_consensus_norman.json"
    must_exist: false
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ws_consensus"
    info: null
    example:
    - "resources_test/grn_benchmark/prior/ws_consensus_norman.csv"
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ws_distance_background"
    info: null
    example:
    - "resources_test/grn_benchmark/prior/ws_distance_background_norman.csv"
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ground_truth_unibind"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ground_truth_chipatlas"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--ground_truth_remap"
    info: null
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_hallmark_2020"
    description: "Hallmark 2020 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_kegg_2021"
    description: "KEGG 2021 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_reactome_2022"
    description: "Reactome 2022 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_go_bp_2023"
    description: "GO Biological Process 2023 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_bioplanet_2019"
    description: "BioPlanet 2019 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--geneset_wikipathways_2019"
    description: "WikiPathways 2019 geneset GMT file"
    info: null
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--scores"
    info: null
    default:
    - "score_uns.yaml"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--metric_configs"
    info: null
    default:
    - "metric_configs.yaml"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
- name: "Arguments"
  arguments:
  - type: "string"
    name: "--metric_ids"
    description: "A list of metric ids to run. If not specified, all metric will be\
      \ run."
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
info:
  label: "run_grn_evaluation"
  summary: "Evaluates GRNs and provides scores using regression analysis."
status: "enabled"
scope:
  image: "public"
  target: "public"
dependencies:
- name: "metrics/regression"
  repository:
    type: "local"
- name: "metrics/ws_distance"
  repository:
    type: "local"
- name: "metrics/tf_recovery"
  repository:
    type: "local"
- name: "metrics/vc"
  repository:
    type: "local"
- name: "metrics/rc_tf_act"
  repository:
    type: "local"
- name: "metrics/sem"
  repository:
    type: "local"
- name: "metrics/anchor_regression"
  repository:
    type: "local"
- name: "metrics/tf_binding"
  repository:
    type: "local"
- name: "metrics/gs_recovery"
  repository:
    type: "local"
- name: "utils/extract_uns_metadata"
  repository:
    type: "github"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
repositories:
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "build/main"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_grn_inference"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      veryhighmem: "memory = 200.Gb"
      veryveryhighmem: "memory = 300.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
      twodaytime: "time = 28.h"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/run_grn_evaluation/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/run_grn_evaluation"
  executable: "target/nextflow/workflows/run_grn_evaluation/main.nf"
  viash_version: "0.9.4"
  git_commit: "f17e9e139ba92e688ddb34a03795a049067a8814"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
  dependencies:
  - "target/nextflow/metrics/regression"
  - "target/nextflow/metrics/ws_distance"
  - "target/nextflow/metrics/tf_recovery"
  - "target/nextflow/metrics/vc"
  - "target/nextflow/metrics/rc_tf_act"
  - "target/nextflow/metrics/sem"
  - "target/nextflow/metrics/anchor_regression"
  - "target/nextflow/metrics/tf_binding"
  - "target/nextflow/metrics/gs_recovery"
  - "target/dependencies/github/openproblems-bio/openproblems/build/main/nextflow/utils/extract_uns_metadata"
package_config:
  name: "task_grn_inference"
  version: "build_main"
  label: "GRN Inference"
  summary: "Article: [geneRNIB: a living benchmark for gene regulatory network inference](https://www.biorxiv.org/content/10.1101/2025.02.25.640181v1)\n\
    \nLeaderboard: \n[Leaderboard](https://genernib-documentation.readthedocs.io/en/latest/leaderboard.html)\n\
    \nDocumentation: \n[geneRNBI-doc](https://genernib-documentation.readthedocs.io/en/latest/)\n\
    \nIf you use this framework, please cite\n\n```\n  @article{nourisa2025genernib,\n\
    \    title={geneRNIB: a living benchmark for gene regulatory network inference},\n\
    \    author={Nourisa, Jalil and Passemiers, Antoine and Stock, Marco and Zeller-Plumhoff,\
    \ Berit and Cannoodt, Robrecht and Arnold, Christian and Tong, Alexander and Hartford,\
    \ Jason and Scialdone, Antonio and Moreau, Yves and others},\n    journal={bioRxiv},\n\
    \    pages={2025--02},\n    year={2025},\n    publisher={Cold Spring Harbor Laboratory}\n\
    \  }\n```\n"
  description: "\ngeneRNIB is a living benchmark platform for GRN inference. This\
    \ platform\nprovides curated datasets for GRN inference and evaluation, standardized\n\
    evaluation protocols and metrics, computational infrastructure, and a\ndynamically\
    \ updated leaderboard to track state-of-the-art methods. It\nruns novel GRNs in\
    \ the cloud, offers competition scores, and stores them\nfor future comparisons,\
    \ reflecting new developments over time.\n\nThe platform supports the integration\
    \ of new inference methods, datasets\nand protocols. When a new feature is added,\
    \ previously evaluated GRNs\nare re-assessed, and the leaderboard is updated accordingly.\
    \ The aim is\nto evaluate both the accuracy and completeness of inferred GRNs.\
    \ It is\ndesigned for both single-modality and multi-omics GRN inference.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/grn"
      dest: "resources_test"
    readme: "## Installation\nInstall Docker, Java, and Viash using\n[these instructions](https://openproblems.bio/documentation/fundamentals/requirements).\n\
      \n## Download resources\n```bash\ngit clone --recursive git@github.com:openproblems-bio/task_grn_inference.git\n\
      \ncd task_grn_inference\n```\nTo interact with the framework,download the resources\
      \ containing necessary inferene and evaluation datasets. \n\n```bash\npip install\
      \ awscli\naws s3 sync  s3://openproblems-data/resources/grn/grn_benchmark resources/grn_benchmark\
      \  --no-sign-request\n\n```\n\n\n## Run a GRN inference method \n\nTo infer\
      \ a GRN for a given dataset (e.g. `op`) using simple Pearson correlation:\n\n\
      ```bash\nviash run src/methods/pearson_corr/config.vsh.yaml -- \\\n        \
      \    --rna resources/grn_benchmark/inference_data/op_rna.h5ad \\\n         \
      \   --tf_all resources/grn_benchmark/prior/tf_all.csv \\ \n            --prediction\
      \ output/net.h5ad\n```\n\n## Evaluate a GRN model\n\n```bash\nbash scripts/run_grn_evaluation.sh\
      \ \\\n            --prediction=output/net.h5ad \\\n            --dataset=op\
      \ \\ \n            --build_images=true \\ \n            --save_dir=output \n\
      ```\n`build_images` only needed for the first run.\n\nThis outputs the scores\
      \ into `output/score_uns.yaml`. \n\n\n## Add a GRN inference method, evaluation\
      \ metric, or dataset\n\nTo add a new component to the repository, follow the\
      \ [Documentation](https://genernib-documentation.readthedocs.io/en/latest/).\n\
      \n## Run the entire pipline\n\nRun `scripts/run_all.sh` for the entire pipeline.\
      \ Due to resource intensive nature of the task, we have splitted the pipeline\
      \ into two steps of GRN inference and evaluation.\n"
  repositories:
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "build/main"
  viash_version: "0.9.4"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\",  veryhighmem : \"\
    memory = 200.Gb\", veryveryhighmem : \"memory = 300.Gb\", lowcpu : \"cpus = 5\"\
    , midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\", midtime\
    \ : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time = 24.h\"\
    , twodaytime : \"time = 28.h\" }\n"
  authors:
  - name: "Jalil Nourisa"
    roles:
    - "author"
    info:
      github: "janursa"
      orcid: "0000-0002-7539-4396"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Jérémie Kalfon"
    roles:
    - "contributor"
    info:
      github: "jkobject"
  - name: "Antoine Passimier"
    roles:
    - "contributor"
    info:
      github: "AntoinePassemiers"
  - name: "Marco Stock"
    roles:
    - "contributor"
    info:
      github: "stkmrc"
  - name: "Christian Arnold"
    roles:
    - "contributor"
    info:
      github: "chrarnold"
  keywords:
  - "gene regulatory network"
  - "network inference"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_grn_inference"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_grn_inference/issues"
