__merge__: ../../api/comp_process_dataset.yaml
functionality:
  name: process_dataset
  namespace: "workflows"
  arguments:
    - name: "--dataset_id"
      type: string
      description: Unique identifier of the dataset.
      required: true
    - name: "--dataset_name"
      type: string
      description: Nicely formatted name.
      required: true
    - name: "--dataset_url"
      type: string
      description: Link to the original source of the dataset.
      required: false
    - name: "--dataset_reference"
      type: string
      description: Bibtex reference of the paper in which the dataset was published.
      required: false
    - name: "--dataset_summary"
      type: string
      description: Short description of the dataset.
      required: true
    - name: "--dataset_description"
      type: string
      description: Long description of the dataset.
      required: true
    - name: "--dataset_organism"
      type: string
      description: The organism of the dataset.
      required: true
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: process_dataset/compute_pseudobulk
    - name: process_dataset/filter_obs
    - name: process_dataset/filter_vars
    - name: process_dataset/add_uns_metadata
    - name: process_dataset/run_limma
    - name: process_dataset/generate_id_map
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
