functionality:
  name: "scglue"
  namespace: "grn_methods"
  version: "build-main"
  arguments:
  - type: "file"
    name: "--multiomics_rna"
    info:
      label: "multiomics rna"
      summary: "RNA expression for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources_test/grn-benchmark/multiomics_rna.h5ad"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--multiomics_atac"
    info:
      label: "multiomics atac"
      summary: "Peak data for multiomics data."
      file_type: "h5ad"
      slots:
        obs:
        - name: "cell_type"
          type: "string"
          description: "The annotated cell type of each cell based on RNA expression."
          required: true
        - name: "donor_id"
          type: "string"
          description: "Donor id"
          required: true
    example:
    - "resources_test/grn-benchmark/multiomics_atac.h5ad"
    must_exist: false
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--prediction"
    info:
      label: "GRN"
      summary: "GRN prediction"
      file_type: "csv"
      columns:
      - name: "source"
        description: "Source of regulation"
        type: "string"
        required: true
      - name: "target"
        description: "Target of regulation"
        type: "string"
        required: true
      - name: "weight"
        description: "Weight of regulation"
        type: "float"
        required: true
    example:
    - "output/grn.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--temp_dir"
    info: null
    default:
    - "output/temdir"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--num_workers"
    info: null
    default:
    - 4
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--tf_all"
    info: null
    example:
    - "resources/prior/tf_all.csv"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "integer"
    name: "--max_n_links"
    info: null
    default:
    - 50000
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--annotation_file"
    info: null
    example:
    - "resources_test/supplementary/gencode.v45.annotation.gtf.gz"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--motif_file"
    info: null
    example:
    - "resources_test/supplementary/JASPAR2022-hg38.bed.gz"
    must_exist: true
    create_parent: true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "main.py"
  test_resources:
  - type: "python_script"
    path: "src/common/component_tests/run_and_check_output.py"
    is_executable: true
  - type: "file"
    path: "resources/grn-benchmark"
    dest: "resources/grn-benchmark"
  - type: "file"
    path: "resources/prior"
    dest: "resources/prior"
  info:
    label: "scglue"
    summary: "GRN inference using scglue"
    description: "GRN inference using scglue. \n"
    documentation_url: "https://scglue.readthedocs.io/"
    type: "methods"
    type_info:
      label: "Method"
      summary: "A GRN inference method"
      description: "A method for inferring GRN from expression data.\n"
  status: "enabled"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:24.06-py3"
  target_organization: "openproblems-bio/task_grn_inference"
  target_registry: "ghcr.io"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openproblems-bio/task_grn_inference"
  setup:
  - type: "python"
    user: false
    packages:
    - "scglue==0.3.2"
    - "pyscenic==0.12.1"
    - "numpy==1.23.4"
    - "scanpy"
    - "networkx"
    - "pyarrow"
    - "cytoolz"
    - "scikit-misc"
    - "cuda-python"
    upgrade: true
  - type: "apt"
    packages:
    - "bedtools"
    interactive: false
  entrypoint: []
  cmd: null
- type: "native"
  id: "native"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "oneweektime"
    - "midmem"
    - "highcpu"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      onedaytime: "time = 24.h"
      threedaystime: "time = 72.h"
      oneweektime: "time = 168.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/task_grn_inference/task_grn_inference/src/methods/multi_omics/scglue/config.vsh.yaml"
  platform: "native"
  output: "/home/runner/work/task_grn_inference/task_grn_inference/target/native/grn_methods/scglue"
  executable: "/home/runner/work/task_grn_inference/task_grn_inference/target/native/grn_methods/scglue/scglue"
  viash_version: "0.8.6"
  git_commit: "11ddcf070be656f617c55de2e6460aaad6ca11e9"
  git_remote: "https://github.com/openproblems-bio/task_grn_inference"
