__merge__: ../../api/comp_metric.yaml

name: ar
namespace: "metrics"
info:
  label: Anchor Regression
  summary: Anchor regression metric for evaluating model robustness

resources:
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/util.py
    dest: util.py
  - path: /src/utils/config.py
    dest: config.py

engines:
  - type: docker
    image: python:3.10
    __merge__: /src/api/base_requirements.yaml
    setup:
      - type: python
        packages: [ ]
        
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [ midtime, highmem, highcpu ]
