
__merge__: ../../api/comp_test.yaml

functionality:
  name: process_perturbation
  namespace: "workflows"
  info:
    label: process_perturbation
    summary: "Processes perturbation data from sc counts to batch corrected perturbation_data"

  arguments:
    - name: --perturbation_counts
      type: file 
      required: true
      direction: input
      default: resources/datasets_raw/perturbation_counts.h5ad
      description: single cell perturbation data 

    - name: --perturbation_data_bc
      __merge__: ../../api/file_perturbation_h5ad.yaml
      required: true
      direction: output
    
    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    - name: perturbation/sc_counts 
    - name: perturbation/normalization
    - name: perturbation/batch_correction_scgen
    - name: perturbation/batch_correction_seurat 

platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
